_target_: segmentation_models_pytorch.Unet

# choose encoder, e.g. mobilenet_v2 or efficientnet-b7
encoder_name: resnet34

# use `imagenet` pre-trained weights for encoder initialization
encoder_weights: imagenet

# model input channels (1 for gray-scale images, 3 for RGB, etc.)
in_channels: 3

classes: 4
