_target_: self_attention_cv.UnetTr.UNETR

img_shape:
  - 128
  - 128
  - 128
input_dim: 1
output_dim: 5
num_heads: 10
embed_dim: 384
patch_size: 16
dropout: 0.0
ext_layers:
  - 3
  - 6
  - 9
  - 12
norm: instance
base_filters: 16
dim_linear_block: 3072
