defaults:
  - _self_
  - data: ckb.yaml
  - model: unet2d.yaml
  - loss: dice_cce.yaml
  - optim: radam.yaml
  - sched: onecycle.yaml
  - metrics: default.yaml
  - hydra: default.yaml

device: cuda
epoch: 50
fp16: false

# seed for random number generators in pytorch, numpy and python.random
seed: 12345
